#TODO вынести пароли в отдельный файл

file-server:
  hostname: localhost
  port: 51234
  user:
    name: blog-api
    password: blog
  path:
    system: /system
    root: /
    avatar: /avatar

blog:
  url: http://localhost:8081
  authorization: 95b0eb6a

encryption:
  password: excalibur
  salt: 76249f7ea5a3cc9e
  active: true

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
